package com.github.sneakytowelsuit.purerules.context.probabilistic;

public sealed interface ProbabilisticConditionEvaluationContextValue permits ProbabilisticRuleEvaluationContextValue, ProbabilisticRuleGroupEvaluationContextValue {
}
